### ISSUE TITLE
status of the container changes to exited(1)

### ISSUE THREAD

**Issue by lukasz-kuch** [0x111/servicenow-instance-wakeup#17]
Image created, build..After running status of the container changes to exited(1) automatically. Port 9222/tcp not bounded
I'm using docker on Windows 10 (docker container- Linux).

**Comment by 0x111** [comment]
Yep, they've changed up a thing or two with the developer portal page. The URL worked before releasing the docker version.

I will look into this, thanks for reporting!

**Comment by 0x111** [comment]
In the meanwhile, to your question, the point of this app is, that it starts up, opens the dev portal, clicks the Wake up button and then it does exit. So the container must not run 24/7 since it does not make sense. You just need to start the app once after your instance goes to sleep.

The behaviour should be correct, although right now there is a bug with it not doing what it is supposed to. There is also a timeout for the context to exit after 60 seconds, because this whole process should not take more than 60 seconds in general. 

We are also not waiting for the instance to wake up, because that could take seconds, sometimes minutes and it is not really necessary for us as an information.

This is only to ease your part in the process (waiting for pages to load, filling out forms, submitting them and waiting...).

**Comment by 0x111** [comment]
@lukasz-kuch  please see the PR here https://github.com/0x111/servicenow-instance-wakeup/pull/18 and give some feedback. You can find all the information there :) for now only binaries (docker build in progress, but for testing the binaries are easier), but I think all the relevant platforms are there and you can run some tests. I appreciate your effort!

**Comment by lukasz-kuch** [comment]
@0x111 thanks. Of course I will inform you with the result!!!

**Comment by 0x111** [comment]
Should be fixed in v0.5
