### ISSUE TITLE
Unable to find status bar?

### ISSUE THREAD

**Issue by jconallen** [0x111/servicenow-instance-wakeup#38]
I am getting the following output:

```
Clicking the next button...
Clicked Next button
Searching for the password field...
Found password field
Filling out the password field...
Filled password field with your password ******
Clicking the submit button...
Clicked Submit button
Login successful!
Detecting the wakeup button element to determine if we are on the developer portal homepage...
could not find shadow element (header status bar): context deadline exceeded
```

Did something change on the snow side?

**Comment by 0x111** [comment]
They redesign stuff every now and then, so that might be the case. Thanks for reporting!
I will check it in the upcoming days/weeks. In the meanwhile, I would kindly ask you to double-check the credentials provided.

There is no complex error handling in the app, because they change it too often and the process is ridiculous enough to don't put too much effort in it. I will get back to you nonetheless.

**Comment by jconallen** [comment]
Thanks, I thought that was the case.  Credentials checked.  Looking forward to trying this out.

**Comment by 0x111** [comment]
Sorry for the delay, I will check it this weekend.

**Comment by 0x111** [comment]
I can confirm this happens due to the new "Cookie confirmation popup" and the overlay.

Can you confirm that the instance is still woken up? @jconallen 

For me it seems to be working fine. I will adjust the app though, I do not care about the button anymore, I will simplify the logic to being logged in, since the URL initiates the wakeup process, that can take 30 seconds, 1 minute, whatever minute. Depending on the situation.

**Comment by jconallen** [comment]
I think it is working (instance is woken up), but the console still displays this message.

So as far as I am concerned things are OK (I can just ignore the message).

Thanks!

**Comment by 0x111** [comment]
Thanks for the confirmation. You are totally correct in the console message being displayed incorrectly so I will modify the behavior and make it more clearer on what is happening.

**Comment by 0x111** [comment]
@jconallen The latest release v0.5.3 should fix this issue.
Docker images have been tagged as latest and v0.5.3
