### ISSUE TITLE
could not set viewport: context canceled

### ISSUE THREAD

**Issue by sachinsp14** [0x111/servicenow-instance-wakeup#41]
Trying to run the wake up instance code inside a docker container and seeing the following error. Can you help me with this. 
"could not set viewport: context canceled"

**Comment by 0x111** [comment]
Hi,

Could you please provide more context, like what version did you download, how are you using it, what commands etc.?
The error you posted means that it can't even set the viewport in the first step, so there must be something fundamentally wrong in your setup.

**Comment by sachinsp14** [comment]
This is the command i used - go run /root/servicenow/servicenow-instance-wakeup.go -username **** -password **** -headless true
I am using the latest version. It runs fine on my local Mac setup, but when i run inside of a docker see that error.

**Comment by 0x111** [comment]
Locally you have chrome/chromium based browser installed, so that is probably why it worked locally. In a docker container, you need the same.

Although I recommend not to run the command manually, but rather use the Docker images I provide here to run the software, those should work, because they are running chrome in headless mode.

Refer to the Docker section [here](https://github.com/0x111/servicenow-instance-wakeup#docker) please.

**Comment by 0x111** [comment]
I am closing this for now, since there was no answer for nearly two weeks now. I assume this is resolved. If not please reopen.

Running the app using the docker image should work if you can't run it locally for some reason.
